### ISSUE TITLE
incus-base : Depends: sgdisk but it is not installable

### ISSUE THREAD

**Issue by nalakawula** [zabbly/incus#23]
I believe sgdisk is provided by [gdisk package](https://packages.debian.org/bookworm/gdisk)

```
✦ > sudo apt install incus
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 incus-base : Depends: sgdisk but it is not installable
E: Unable to correct problems, you have held broken packages
```

Thank you

**Comment by fredluetkemeier** [comment]
I'm having the exact same issue. Any fix for this?

**Comment by stgraber** [comment]
A fix has been pushed to the repository, it will roll out in a couple of hours.

**Comment by fredluetkemeier** [comment]
@stgraber Thank you!

**Comment by stgraber** [comment]
Sorry about that, normally all changes to stable get staged for a few days in daily, but with the 0.5.1 release, things got shuffled around a fair bit and that change propagated to stable before it even landed in daily...

The error comes from the Incus dependency being sgdisk but the Debian/Ubuntu package for that being just gdisk... Because of the timing above, our CI caught it, but only once it made it to daily which at that point was already too late due to stable having published at the time time.

**Comment by fredluetkemeier** [comment]
No worries, thanks for the quick turnaround!

**Comment by stgraber** [comment]
It's been published now
