### ISSUE TITLE
OpenID with Microsoft Entra ID: cannot unmarshal string into Go struct field .expires_in

### ISSUE THREAD

**Issue by IAmFrench** [zabbly/incus#65]
## Incus version (remote)

```bash
incus --version
6.7
```

## Incus config

```bash
incus config show
config:
  core.https_address: '[::]:8443'
  oidc.audience: https://login.microsoftonline.com/redacted_tenant_id_here/oauth2/v2.0/
  oidc.client.id: redacted_client_id_here
  oidc.issuer: https://sts.windows.net/redacted_tenant_id_here/
```

### App Registrations > My App for Incus > Authentication
![image](https://github.com/user-attachments/assets/c2e6d976-609b-4ea7-8892-bce8b43a2c5d)
![image](https://github.com/user-attachments/assets/5c481a50-d654-4128-8d60-75a7814570a8)

Redirect URL for Mobile and desktop applications is set to: `https://192.168.20.35:8443/oidc/callback`
# Issue

Hello!
I'm able to complete the authentication flow, but Incus UI is not able to load the project page and then disconnect.
Certificate-based login works.

## Error (From browser developer tools > Network)

```
GET https://192.168.20.35:8443/1.0

Failed to authenticate: failed to unmarshal response: json: cannot unmarshal string into Go struct field AccessTokenResponse.expires_in of type uint64 {"token_type":"Bearer","expires_in":"3599","ext_expires_in":"3599","expires_on":"1733519689","access_token":"redacted","refresh_token":"redacted","id_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.redacted.redacted"}
```

![image](https://github.com/user-attachments/assets/2708a9d4-375b-4a77-9da1-9eefb4766683)

## Error using the inclus client (on Windows)

I'm not able to connect using `--auth-type=oidc`: the connection is closed, launching the `incus remote add` command will generate a new code each time.

```powershell
incus --version
6.7
```

```powershell
incus remote add main 192.168.20.35 --auth-type=oidc
Certificate fingerprint: redacted
ok (y/n/[fingerprint])? y
Error: failed to unmarshal response: json: cannot unmarshal string into Go struct field .expires_in of type int {"user_code":"REDACTED","device_code":"REDACTED","verification_url":"https://microsoft.com/devicelogin","expires_in":"900","interval":"5","message":"To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code REDACTED to authenticate."}
```

**Comment by stgraber** [comment]
So unfortunately this is a problem that's external to us.

Our logic uses https://github.com/zitadel/oidc for OpenID Connect handling. This is a fully complaint and certified OIDC implementation.

The OIDC spec specifies that `expires_in` is an integer, not a string, so the error is unfortunately correct.

Googling around for this, it looks like you may be able to change the Entra ID application from v1.0 to v2.0 for the access token which may fix this issue?

Otherwise you could try to see if the zitadel folks want to make the parser more lenient, but given this would literally be against the spec, that seems unlikely. One last option would be to go through Keycloak or a similar OIDC provider as an intermediary between Entra and Incus, assuming that Keycloak is fine with a non-compliant server.
